### ISSUE TITLE
fd_read hangs

### ISSUE THREAD

**Issue by kristoff-it** [microsoft/vscode-wasm#178] opened 2024-07-10 22:11 UTC
While working to get my Language Server to run in VSCode from WASM, I was able to get everything setup except I noticed that it would never successfully complete the initial handshake.

After some investigative work I realized that the first read "syscall" succeeds, while the second one hangs presumably because of a bug in the WASI layer related to partial reads.

Verified this issue both from Zig and Rust, where a trivial echo server with a small buffer (or even better directly calling fd_read) only succeeds once.

Conversely I tested that by increasing the size of my read buffer I'm able to have the language server run until I try to open a file that results in a big-enough message to trigger a partial read.

Example Rust code: 
```rs
use std::io::{self, Read};
fn main() {
    let stdin = io::stdin();
    let mut handle = stdin.lock();
    let mut buffer = [0; 100]; 

    loop {
        match handle.read(&mut buffer) {
            Ok(n) if n > 0 => {
                eprint!("{}", String::from_utf8_lossy(&buffer[..n]));
            }
            Ok(_) => {
                eprint!("\n\n nothing \n");
                break; // End of input
            }
            Err(error) => {
                eprintln!("Error reading from stdin: {}", error);
                break;
            }
        }
    }
}
```

Dependencies:

```
  "extensionDependencies": [
    "ms-vscode.wasm-wasi-core"
  ],
  "devDependencies": {
    "@types/mocha": "^2.2.48",
    "@types/node": "^18.0.0",
    "@types/vscode": "^1.68.0",
    "@types/which": "^2.0.1",
    "@typescript-eslint/eslint-plugin": "^6.7.0",
    "@typescript-eslint/parser": "^6.7.0",
    "eslint": "^8.49.0",
    "vscode-test": "^1.4.0"
  },
  "dependencies": {
    "@vscode/vsce": "^2.24.0",
    "@vscode/wasm-wasi-lsp": "^0.1.0-pre.6",
    "camelcase": "^7.0.1",
    "esbuild": "^0.12.1",
    "lodash-es": "^4.17.21",
    "lodash.debounce": "^4.0.8",
    "mkdirp": "^2.1.3",
    "vscode-languageclient": "^10.0.0-next.3",
    "which": "^3.0.0"
  },
```

**Comment by dbaeumer** [comment] 2024-08-28 18:29
Thanks for the great repro. 

Investigated and is a duplicate of https://github.com/microsoft/vscode-wasm/issues/110 which I fixed today.

**Closed by dbaeumer** 2024-08-28 18:29 UTC

**Comment by kristoff-it** [comment] 2024-08-28 18:39
Awesome, thank you very much!

**Comment by kristoff-it** [comment] 2024-09-04 15:39
Tried today to make this work but I'm still encountering the same problem. I've updated the `vscode-wasi-core` extension to v1.0.0, which I believe should contain #189.

**Comment by kristoff-it** [comment] 2024-09-07 17:46
@dbaeumer can you please confirm if the fix made it into the v1.0.0 release of the wasi-core extension?

Also, just a hunch: the other issue mentioned writing to a file descriptor, while in my case it's reading from one, and in both cases we were talking about it from the perspective of the WASM code. Could it be that the same fix that you applied for writing needs to be replicated for the read case?

**Comment by dbaeumer** [comment] 2024-09-09 06:58
The fix is in v1.0.0. And I fixed it for the read and writing side. Please ping if you still see issues.

**Comment by kristoff-it** [comment] 2024-09-09 14:15
I can confirm this bug was fixed and found another problem that I will create a dedicated issue for. Thanks again.

**Comment by kristoff-it** [comment] 2024-09-09 15:54
Nevermind,  the problem seems to still be this. 

To reproduce the problem with Rust we need to write to a buffer more than 8kb.

Here are some steps:

1. Build this echo server for wasm32-wasi:
```rust
fn main() {
    let stdin = io::stdin();
    let mut handle = stdin.lock();
    let mut buffer = [0; 1];
    let mut acc = 0usize;
    eprint!("Rust Echo\n");
    loop {
        match handle.read(&mut buffer) {
            Ok(n) if n > 0 => {
                eprint!("({}) '{}'\n", acc, String::from_utf8_lossy(&buffer[..n]));
                acc += 1;
            }
            Ok(_) => {
                eprint!("\n\n nothing \n");
                break; // End of input
            }
            Err(error) => {
                eprintln!("Error reading from stdin: {}", error);
                break;
            }
        }
    }
}
```
2. Write an LSP WASI extension and in the `activate` callback print enough data to stdin before calling `startServer`:
```typescript
// ...
for (let i = 0; i < 8190; i++) {
    await process.stdin!.write("a");
}

await process.stdin!.write("success");

return startServer(process);
```

3. Debug the extension, observe how the reads stop at the first two letters of "success" (which is exactly 8192 bytes, 8kb)

```
...
(8187) 'a'
(8188) 'a'
(8189) 'a'
(8190) 's'
(8191) 'u'
```

With Zig I've been able to experience this issue at various stop points depending on how I configured read buffering. In rust buffering is hardcoded at 8k, hence the necessity to pump extra bytes.



Could probably be reproduced without needing the LSP boilerplate, but that's how I've experienced it and wouldn't be able to give precise instructions otherwise.

**Comment by mlugg** [comment] 2024-09-09 16:06
The logic in `Stream.read` seems completely bogus. Specifically, the multi-chunk case (the `else` statement after the comment, `streams.ts:106`) has a myriad of trivial logic errors:
* The initial loop doesn't actually increment `resultSize`, so the loop is a nop.
* The following loop shifts chunks before checking whether they'll be included in the output, causing some chunks to be silently dropped.
* Chunks are shifted in a loop which iterates chunks based on index, so we will skip some chunks since `length` is decreasing as `i` increases

I haven't tested it, but I think the following patch should work:
```diff
diff --git a/wasm-wasi-core/src/common/streams.ts b/wasm-wasi-core/src/common/streams.ts
index c5d7e5e..2530a8d 100644
--- a/wasm-wasi-core/src/common/streams.ts
+++ b/wasm-wasi-core/src/common/streams.ts
@@ -108,14 +108,15 @@ export abstract class Stream {
                                if (resultSize + this.chunks[i].byteLength > maxBytes) {
                                        break;
                                }
+                               resultSize += this.chunks[i].byteLength;
                        }
                        const result = new Uint8Array(resultSize);
                        let offset = 0;
-                       for (let i = 0; i < this.chunks.length; i++) {
-                               const chunk = this.chunks.shift()!;
-                               if (offset + chunk.byteLength > maxBytes) {
+                       while (this.chunks.length > 0) {
+                               if (offset + this.chunks[0].byteLength > maxBytes) {
                                        break;
                                }
+                               const chunk = this.chunks.shift()!;
                                result.set(chunk, offset);
                                offset += chunk.byteLength;
                                this.fillLevel -= chunk.byteLength;
```

**Comment by mlugg** [comment] 2024-09-09 17:49
There's actually a second bug here, too. `pipeDriver.ts` defines this `Stdin` interface, used by its `export function create`:

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/pipeDriver.ts#L27-L29

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/pipeDriver.ts#L35

That `create` is called from exactly one place, in `process.ts`, with that argument being `this._stdin`, which is a `WritableStream`:

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/process.ts#L440

However, `WritableStream` does not conform to the given `Stdin` interface. It doesn't directly expose any `read` method, and its superclass `Stream` only exposes a different set of signatures:

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/streams.ts#L65-L67

TypeScript fails to pick up on the interface violation here. This leads to `mode` being incorrectly passed as `maxBytesToRead` in the `fd_read` handler:

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/pipeDriver.ts#L85

So, `Stream.read` notices that `mode !== 'max'`, meaning it sets `maxBytes` to `undefined`, representing "no maximum":

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/streams.ts#L68

Logic further down that function notices this case, and just flushes all of the chunks into the output buffer:

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/streams.ts#L82-L94

Finally, the logic back in `fd_read` copies the correct amount of data to the output buffers, silently dropping any data exceeding the read size:

https://github.com/microsoft/vscode-wasm/blob/900a2f86d96f6076132b4f9df9765117e757e3ae/wasm-wasi-core/src/common/pipeDriver.ts#L88-L96

This explains the behavior @kristoff-it saw above, where all data up to the 8k read size was correctly read (which you *wouldn't* expect from the buggy path I covered in my previous comment), but any data following that was dropped. I confirmed that TypeScript fails to identify this interface violation by running the following test code which is a skeleton of the logic outlined above:

<details>
<summary>test code</summary>

```ts
class Stream {
    public async read(): Promise<Uint8Array>;
	public async read(mode: 'max', size: number): Promise<Uint8Array>;
	public async read(mode?: 'max', size?: number): Promise<Uint8Array> {
        if (mode === 'max') {
            return Promise.resolve(new Uint8Array([0]));
        } else {
            return Promise.resolve(new Uint8Array([1]));
        }
    }
}

interface Stdin {
    // this doesn't match the Stream interface
    read(maxBytesToRead: number): Promise<Uint8Array>;
}

async function foo(stdin: Stdin | undefined) {
    if (stdin !== undefined) {
        const maxBytesToRead: number = 123;
        const result = await stdin.read(maxBytesToRead);
        console.log(result[0]); // prints 1, indicating mode was not max
    }
}

let _stdin = new Stream();
foo(_stdin as Stream)
```

</details>

The fix here is just to correct the `Stdin` interface definition and corresponding `read` call in `pipeDriver.ts`:

```ts
interface Stdin {
    read(mode: 'max', maxBytesToRead: size): Promise<Uint8Array>;
}

// in fd_read...
const result = await stdin.read('max', maxBytesToRead);

```

**Comment by dbaeumer** [comment] 2024-09-10 07:39
@mlugg thanks for the great analysis. I opened https://github.com/microsoft/TypeScript/issues/59922 on the TypeScript side since this is the actual cause.

**Comment by dbaeumer** [comment] 2024-09-10 08:19
Added a test case: https://github.com/microsoft/vscode-wasm/pull/197

**Comment by mlugg** [comment] 2024-09-10 08:24
Thanks. Any chance of a patch release soon so that @kristoff-it doesn't have to use a locally patched version of the extension? This bug made stdio (and other streams) unusable for large amounts of data.

**Comment by dbaeumer** [comment] 2024-09-11 08:52
1.0.2 is available.
